#!/bin/bash

BASE_NAME=$0

function printUsage()
{
    echo "sh $BASE_NAME [options]"
    echo " -o result output file path"
    echo " -m mysql path"
    echo " -u mysql username"
    echo " -p mysql password"
    echo " -D mysql database"
    echo " -h mysql host"
    echo " -P mysql port"
    echo " [optional] -s start picture id. default it's 0"
    echo " [optional] -e end picture id, 0 means to end. default it's 0"
    echo " [optianal] -t echo dump lines. default it's 10000"
}

START_DUMP_POS=0
END_DUMP_POS=0
DUMP_STEP=10000
RESULT_OUTPUT_PATH=""
MYSQL_BIN=""
MYSQL_USER=""
MYSQL_PASSWORD=""
MYSQL_DATABASE=""
MYSQL_HOST=""
MYSQL_PORT=3306

while getopts s:e:c:o:m:u:p:D:h:P:t: option
do
    case $option in
        m) MYSQL_BIN=$OPTARG
            echo "MYSQL_BIN=$MYSQL_BIN"
            ;;
        u) MYSQL_USER=$OPTARG
            echo "MYSQL_USER=$MYSQL_USER"
            ;;
	t) DUMP_STEP=$OPTARG
	    echo "DUMP_STEP=$DUMP_STEP"
	    ;;
        p) MYSQL_PASSWORD=$OPTARG
            echo "MYSQL_PASSWORD=$MYSQL_USER"
            ;;
        D) MYSQL_DATABASE=$OPTARG
            echo "MYSQL_DATABASE=$MYSQL_DATABASE"
            ;;
        h) MYSQL_HOST=$OPTARG
            echo "MYSQL_HOST=$MYSQL_HOST"
            ;;
        P) MYSQL_PORT=$MYSQL_PORT
            echo "MYSQL_PORT=$MYSQL_PORT"
            ;;
        o) RESULT_OUTPUT_PATH=$OPTARG
            echo "RESULT_OUTPUT_PATH=$RESULT_OUTPUT_PATH"
            ;;
        s) START_DUMP_POS=$OPTARG
            echo "START_DUMP_POS=$START_DUMP_POS"
            ;;
        e) END_DUMP_POS=$OPTARG
            echo "END_DUMP_POS=$END_DUMP_POS"
            ;;
        /?) echo "wrong param"
            printUsage
            exit 1
            ;;
    esac
done

if [ "$MYSQL_BIN" = "" -o "$MYSQL_USER" = "" -o "$MYSQL_PASSWORD" = "" -o "$MYSQL_DATABASE" = "" -o "$MYSQL_HOST" = "" -o "$MYSQL_PORT" = "" -o "$START_DUMP_POS" = "" ]; then
   printUsage
   exit 1
fi

# 得到此时最大的goodsid
MAX_GOODSID=`echo "SELECT max(goods_id) FROM t_dolphin_fut_goods_info" | $MYSQL_BIN -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -P$MYSQL_PORT -D$MYSQL_DATABASE | sed '1d'`
echo "============ Get Max goods_id id $MAX_GOODSID"

# 开始导出数据
if [ -f $RESULT_OUTPUT_PATH ]; then rm $RESULT_OUTPUT_PATH; fi

CUR_START_GOODSID=$START_DUMP_POS
if [ $END_DUMP_POS -eq 0 -o $END_DUMP_POS -gt $MAX_GOODSID ]
then
    END_DUMP_POS=$MAX_GOODSID
fi

while [ $CUR_START_GOODSID -lt $END_DUMP_POS ]
do
    cur_max_goodsid=$(($CUR_START_GOODSID+$DUMP_STEP))
    pics=`echo "SELECT goods_picture_id FROM t_dolphin_fut_goods_info WHERE goods_id > $CUR_START_GOODSID AND goods_id < $cur_max_goodsid and goods_picture_id > 0" | $MYSQL_BIN -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -P$MYSQL_PORT -D$MYSQL_DATABASE | sed '1d' | while read item; do printf "%s," $item; done;`
    pics=$pics"-1"
    echo "select picid, n_pic_file from t_picture where picid in ($pics)" | $MYSQL_BIN -u$MYSQL_USER -p$MYSQL_PASSWORD -h$MYSQL_HOST -P$MYSQL_PORT -D$MYSQL_DATABASE | sed '1d' >> $RESULT_OUTPUT_PATH
    CUR_START_GOODSID=$(($CUR_START_GOODSID+$DUMP_STEP))
    echo "============= Dumped $CUR_START_GOODSID lines"
    sleep 1
done
