#ifndef IMAGE_SERVICE_COMMON_CONSTANT_H_
#define IMAGE_SERVICE_COMMON_CONSTANT_H_


enum {
  CR_SUCCESS = 0,

  // common define
  CR_OUTOFMEMORY = 1,
  CR_MEM_ACCESS_VIOLATION,
  CR_NOFILE,
  
  // for mysql
  CR_MYSQL_INIT_FAILED = 100, /* 2 */
  CR_MYSQL_CONNECT_FAILED, /* 3 */
  CR_MYSQL_SELECTDB_FAILED, /* 4 */
  CR_MYSQL_SETCHARSET_FAILED, /* 5 */
  CR_MYSQL_QUERY_FAILED, /* 6 */
  CR_MYSQL_EMPTYQUERYSTORE, /* 7 */
  CR_MYSQL_NOFIELD, /* 8 */
  CR_MYSQL_SETOPTION_FAILED, /* 9 */
  CR_MYSQL_POOL_UNAVAILABLE_SOURCE, /* 10 */

  // for HTTP
  CR_HTTP_BEGIN = 200,
  CR_HTTP_CURL_INIT_FAILED,
  CR_HTTP_SEND_REQUEST_FAILED,
  CR_HTTP_OUT_OF_MEMORY,
  CR_HTTP_WRONG_POST_DATA,
  CR_HTTP_CURL_PERFORM_FAILED,
  CR_HTTP_MEM_ACCESS_VIOLATION,
  CR_HTTP_RETURN_ERROR,
  CR_HTTP_GLOBAL_INIT_FAILED,

  //for jpeg code
  CR_JPEG_CODE_PARAM_ERROR =500,
  CR_JPEG_CODE_OUT_OF_MEM ,
  CR_JPEG_CODE_COMPRESS_FAILED ,
  CR_JPEG_CODE_DECOMPRESS_FAILED ,
  CR_JPEG_CODE_GET_FAILED ,
};

#endif
