#ifndef IMAGE_STORAGE_CLIENT_BEANSDB_CLIENT_CONSTANT_H_
#define IMAGE_STORAGE_CLIENT_BEANSDB_CLIENT_CONSTANT_H_

#define BEANSDB_MAX_BUCKETS (256)
#define BEANSDB_DEFAULT_BUCKET_SERVER_NUM (3)
#define BEANSDB_CLIENT_LOGGER_NAME "beansdbclient"

typedef enum {
  BCR_SUCCESS = 0,
  BCR_MEMCACHED_CREATE_FAILED, /* 1 */
  BCR_MEMCACHED_APPENDSERVERLIST_FAILED, /* 2 */
  BCR_MEMCACHED_PUSHSERVER_FAILED, /* 3 */
  BCR_MEMCACHED_NOTFOUND, /* 4 */
  BCR_MEMCACHED_GET_FAILED, /* 5 */
  BCR_MEMCACHED_SET_FAILED, /* 6 */
  BCR_MEMCACHED_DELETE_FAILED, /* 7 */
  BCR_OUTOFMEMORY, /* 8 */
  BCR_BEANSDB_SAVELESSTHAN2, /* 9 */
  BCR_BEANSDB_OUTOFBUCKET, /* 10 */
  BCR_BEANSDB_GETBUCKET_FAILED, /* 11 */
  BCR_BEANSDB_OUTOFCLIENTS, /* 12 */
  BCR_MEMCACHED_SET_BEHAVIOR_FAILED, /* 13 */
  BCR_POOL_UNAVAILABLE_SOURCE, /* 14 */
  BCR_MEMCACHE_UNCOMPRESS_FAILED, /* 15 */
  BCR_CLUSTER_CONF_FAILED, /* 16 */
  BCR_PARSE_PICKEY_FAILED, /* 17 */
  BCR_NOCLUSTER_FOUND, /* 18 */
} beansdb_client_ret_t;

#endif
