/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ImageSearchMsg_H
#define ImageSearchMsg_H

#include <TProcessor.h>
#include "imgsearch_types.h"



class ImageSearchMsgIf {
 public:
  virtual ~ImageSearchMsgIf() {}
  virtual void Search(ImageSearchResponse& _return, const ImageSearchRequest& request) = 0;
};

class ImageSearchMsgNull : virtual public ImageSearchMsgIf {
 public:
  virtual ~ImageSearchMsgNull() {}
  void Search(ImageSearchResponse& /* _return */, const ImageSearchRequest& /* request */) {
    return;
  }
};

typedef struct _ImageSearchMsg_Search_args__isset {
  _ImageSearchMsg_Search_args__isset() : request(false) {}
  bool request;
} _ImageSearchMsg_Search_args__isset;

class ImageSearchMsg_Search_args {
 public:

  ImageSearchMsg_Search_args() {
  }

  virtual ~ImageSearchMsg_Search_args() throw() {}

  ImageSearchRequest request;

  _ImageSearchMsg_Search_args__isset __isset;

  void __set_request(const ImageSearchRequest& val) {
    request = val;
  }

  bool operator == (const ImageSearchMsg_Search_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const ImageSearchMsg_Search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageSearchMsg_Search_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ImageSearchMsg_Search_pargs {
 public:


  virtual ~ImageSearchMsg_Search_pargs() throw() {}

  const ImageSearchRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ImageSearchMsg_Search_result__isset {
  _ImageSearchMsg_Search_result__isset() : success(false) {}
  bool success;
} _ImageSearchMsg_Search_result__isset;

class ImageSearchMsg_Search_result {
 public:

  ImageSearchMsg_Search_result() {
  }

  virtual ~ImageSearchMsg_Search_result() throw() {}

  ImageSearchResponse success;

  _ImageSearchMsg_Search_result__isset __isset;

  void __set_success(const ImageSearchResponse& val) {
    success = val;
  }

  bool operator == (const ImageSearchMsg_Search_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ImageSearchMsg_Search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageSearchMsg_Search_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ImageSearchMsg_Search_presult__isset {
  _ImageSearchMsg_Search_presult__isset() : success(false) {}
  bool success;
} _ImageSearchMsg_Search_presult__isset;

class ImageSearchMsg_Search_presult {
 public:


  virtual ~ImageSearchMsg_Search_presult() throw() {}

  ImageSearchResponse* success;

  _ImageSearchMsg_Search_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ImageSearchMsgClient : virtual public ImageSearchMsgIf {
 public:
  ImageSearchMsgClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ImageSearchMsgClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Search(ImageSearchResponse& _return, const ImageSearchRequest& request);
  void send_Search(const ImageSearchRequest& request);
  void recv_Search(ImageSearchResponse& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ImageSearchMsgProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<ImageSearchMsgIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (ImageSearchMsgProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_Search(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ImageSearchMsgProcessor(boost::shared_ptr<ImageSearchMsgIf> iface) :
    iface_(iface) {
    processMap_["Search"] = &ImageSearchMsgProcessor::process_Search;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~ImageSearchMsgProcessor() {}
};

class ImageSearchMsgMultiface : virtual public ImageSearchMsgIf {
 public:
  ImageSearchMsgMultiface(std::vector<boost::shared_ptr<ImageSearchMsgIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ImageSearchMsgMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ImageSearchMsgIf> > ifaces_;
  ImageSearchMsgMultiface() {}
  void add(boost::shared_ptr<ImageSearchMsgIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Search(ImageSearchResponse& _return, const ImageSearchRequest& request) {
    size_t sz = ifaces_.size();
    for (size_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->Search(_return, request);
        return;
      } else {
        ifaces_[i]->Search(_return, request);
      }
    }
  }

};



#endif
