/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "imgsearch_constants.h"



const imgsearchConstants g_imgsearch_constants;

imgsearchConstants::imgsearchConstants() {
}



