/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef imgsearch_CONSTANTS_H
#define imgsearch_CONSTANTS_H

#include "imgsearch_types.h"



class imgsearchConstants {
 public:
  imgsearchConstants();

};

extern const imgsearchConstants g_imgsearch_constants;



#endif
