/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "exec_merge_constants.h"



const exec_mergeConstants g_exec_merge_constants;

exec_mergeConstants::exec_mergeConstants() {
}



