/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef exec_merge_CONSTANTS_H
#define exec_merge_CONSTANTS_H

#include "exec_merge_types.h"



class exec_mergeConstants {
 public:
  exec_mergeConstants();

};

extern const exec_mergeConstants g_exec_merge_constants;



#endif
