/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "spatial_ranker_constants.h"



const spatial_rankerConstants g_spatial_ranker_constants;

spatial_rankerConstants::spatial_rankerConstants() {
}



