/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef spatial_ranker_CONSTANTS_H
#define spatial_ranker_CONSTANTS_H

#include "spatial_ranker_types.h"



class spatial_rankerConstants {
 public:
  spatial_rankerConstants();

};

extern const spatial_rankerConstants g_spatial_ranker_constants;



#endif
