#ifndef IMAGE_SERVICE_COMMON_CONSTANT_H_
#define IMAGE_SERVICE_COMMON_CONSTANT_H_


enum {
  CR_SUCCESS = 0,

  CR_OUTOFMEMORY = 1,
  CR_MEM_ACCESS_VIOLATION,
  CR_NOFILE,

  // for gearman
  CR_GEARMAN_INIT_FAILED = 300,
  CR_GEARMAN_CREATE_WORKER_FAILED,
  CR_GEARMAN_ADD_SERVER_FAILED,
  CR_GEARMAN_GRAB_JOB_FAILED,
  CR_GEARMAN_ADD_FUNCTION_FAILED,
  CR_GEARMAN_SEND_RESPONSE_FAILED,
  CR_GEARMAN_ADD_TASK_FAILED,
  CR_GEARMAN_RUN_TASK_FAILED,
  CR_GEARMAN_PARSE_JOB_FAILED,

  // for json parser
  CR_JSON_WRONG_FORMAT = 400,
  CR_JSON_NO_OBJECT,
  CR_JSON_WRONG_XPATH,
  CR_JSON_NOT_ARRAY,
};

#endif
